services:
  app:
    image: laravel-app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    working_dir: /usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: >
      sh -c "
      composer install &&
      php artisan key:generate &&
      php artisan serve --host=0.0.0.0 --port=8000
      "
    depends_on:
      - vite
    networks:
      - laravel_net

  vite:
    image: node:20-alpine
    container_name: vite-dev
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    networks:
      - laravel_net

networks:
  laravel_net:

volumes:
  node_modules:
